name: First Github Action

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        run: actions/checkout@v4

      - name: Print Greeting
        run: echo "Hello from gitHub Actions!"
